package:
  name: scikit-image
  version: 0.21.0rc1
  top-level:
    - skimage
      # - doc  # scikit-image has top level `doc` directory... but it is too common name so we don't want to use it as a hint for top-level import.
source:
  patches:
    - patches/make-tifffile-optional.patch
    - patches/meson-debug.patch
  sha256: 98b7eb01ad1645475440e2f5fed82bc06b657fe31f648bc2a4c163dd3b794e79
  url: https://files.pythonhosted.org/packages/9a/31/ecc1b9d98cd3dcc50fd6e3fe2839fd111c1e43ee356452e2fad189da6d38/scikit_image-0.21.0rc1.tar.gz

build:
  script: |
    echo CFLAGS: $CFLAGS
    echo LDFLAGS: $LDFLAGS
    export CFLAGS=${SIDE_MODULE_CFLAGS}
    export LDFLAGS=${SIDE_MODULE_LDFLAGS/-L /-L}
    echo CFLAGS: $CFLAGS
    echo LDFLAGS: $LDFLAGS
  backend-flags: setup-args=--cross-file=$PYODIDE_ROOT/tools/emscripten.meson.cross builddir=my-build

requirements:
  host:
    - numpy
  run:
    - packaging
    - numpy
    - scipy
    - networkx
    - Pillow
    - imageio
    - pywavelets
    - lazy_loader

about:
  home: https://scikit-image.org
  PyPI: https://pypi.org/project/scikit-image
  summary: Image processing in Python
  license: Modified BSD
# Note: this package cannot be updated until we add support for building with meson
