package:
  name: numpy
  version: 1.25.0dev
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  # url: https://files.pythonhosted.org/packages/42/38/775b43da55fa7473015eddc9a819571517d9a271a9f8134f68fb9be2f212/numpy-1.23.5.tar.gz
  # sha256: 1b1766d6f397c18153d40015ddfc79ddb715cabadc04d2d228d4e5a8bc4ded1a
  url: https://github.com/numpy/numpy/archive/99eaf340c.zip
  sha256: 2b3223dbd9612f4d2a0800bb10a7406cbdb0705b292d2a06906512a368bc7cb0

build:
  backend-flags: --disable-optimization
  cflags: |
    -Wno-return-type
  cross-build-env: true
  cross-build-files:
    - numpy/core/include/numpy/numpyconfig.h
    - numpy/core/include/numpy/_numpyconfig.h
    - numpy/core/lib/libnpymath.a
    - numpy/random/lib/libnpyrandom.a
about:
  home: https://www.numpy.org
  PyPI: https://pypi.org/project/numpy
  summary: NumPy is the fundamental package for array computing with Python.
  license: BSD
